steps:
  # 1. Install dependencies
  - name: 'gcr.io/flutter/flutter:3.24.4'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        flutter pub get

  # 1.5 Set CI Version
  - name: 'gcr.io/cloud-builders/git'
    entrypoint: 'bash'
    args:
      - 'scripts/set_ci_version.sh'

  # 2. Analyze code
  - name: 'gcr.io/flutter/flutter:3.24.4'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        flutter analyze

  # 3. Run tests with coverage
  - name: 'gcr.io/flutter/flutter:3.24.4'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        flutter test --coverage

  # 4. Run Golden Tests explicitly
  - name: 'gcr.io/flutter/flutter:3.24.4'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Explicitly run golden tests to verify UI snapshots.
        flutter test --tags=golden

  # 4. Check coverage
  - name: 'gcr.io/flutter/flutter:3.24.4'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Use existing coverage data to calculate percentage
        # A simple check counting covered lines vs total lines
        # This requires lcov to be installed; using a lightweight awk script if needed
        # We can use format_coverage from flutter or a pure shell approach
        
        # Simple coverage check script:
        TOTAL_LINES=$$(grep -v '^end_of_record' coverage/lcov.info | grep -v '^TN:' | grep -v '^SF:' | wc -l)
        COVERED_LINES=$$(grep '^DA:' coverage/lcov.info | cut -d',' -f2 | grep -v '^0$$' | wc -l)
        
        if [ "$$TOTAL_LINES" -eq 0 ]; then
          echo "No coverage data found."
          exit 1
        fi
        
        PERCENTAGE=$$(( 100 * COVERED_LINES / TOTAL_LINES ))
        echo "Coverage is $$PERCENTAGE%"
        
        if [ "$$PERCENTAGE" -lt 70 ]; then
          echo "Coverage is below 70%! Failing the build."
          exit 1
        fi
        
        echo "Coverage requirement met."

  # 5. Build API Proxy Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'europe-west1-docker.pkg.dev/$PROJECT_ID/showsonar/api-proxy:$COMMIT_SHA',
      '-t', 'europe-west1-docker.pkg.dev/$PROJECT_ID/showsonar/api-proxy:latest',
      'infra/cloud-run/api-proxy'
    ]

  # 6. Push API Proxy Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push',
      '--all-tags',
      'europe-west1-docker.pkg.dev/$PROJECT_ID/showsonar/api-proxy'
    ]

  # 7. Deploy Cloud Run API Proxy
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'api-proxy'
      - '--image'
      - 'europe-west1-docker.pkg.dev/$PROJECT_ID/showsonar/api-proxy:$COMMIT_SHA'
      - '--region'
      - 'europe-west1'
      - '--project'
      - '$PROJECT_ID'

  # 8. Deploy Firestore Security Rules
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        npm install -g firebase-tools
        # Note: In a real CI environment, you'd need FIREBASE_TOKEN or a service account 
        # configured for firebase-tools. Cloud Build service account usually works automatically.
        firebase deploy --only firestore:rules --project $PROJECT_ID

options:
  logging: CLOUD_LOGGING_ONLY
